### PR TITLE
Adding MacPorts as install method

### PR DESCRIPTION
**Pull request by Ci7rix**
Datree was added to MacPorts (https://github.com/macports/macports-ports/pull/16110).
Maybe it could be nice to have it as an install method in the documentation.

### CODE REVIEW

**Comment by eyarz** [comment]
@Ci7rix thank you for adding Datree to MacPorts catalog.
How MacPorts knows to update their binary on a new version release of Datree?

**Comment by Ci7rix** [comment]
@eyarz the port needs to be updated manually by submitting a pull request of the modified Portfile.
I'm "watching" the repo, on a new final release, I submit a pull request.

For this port, it's easy, the lines that need to be modified are the version number and the checksums
https://github.com/macports/macports-ports/blob/master/devel/datree/Portfile

**Comment by eyarz** [comment]
we had a bad experience with manual updates.
Those are usually getting outdated after a few months, and this affects the user experience because they are using an out-of-date version of Datree.

Maybe we can create a new section and list there the manually updated package managers (e.g. MacPorts, [archLinux](https://archlinux.org/packages/?q=datree), etc.) and add a disclaimer that those packages are usually not up to date.

WDYT?

**Comment by Ci7rix** [comment]
I fully understand, it makes perfect sense to me. 
Maybe a "Community maintained packages" section.

Two examples that come to mind that have this disclaimer are the Netdata [0] and step-ca [1] documentation.

Maybe the easiest way would be to group the installation methods by OS and add the manually updated section under the official ones.

Let me know if I can do anything.

[0] https://learn.netdata.cloud/docs/agent/packaging/installer/methods/macos
[1] https://smallstep.com/docs/step-ca/installation

**Comment by eyarz** [comment]
so let's add a new section - "Others" and add the disclaimer + installation instructions for MacPort there.
here is a mock:
image

do you want to update your PR to meet this specification?

**Comment by Ci7rix** [comment]
Hi @eyarz, I added the section and the disclaimer

**Review by hadar-co — APPROVED** [review]
Nice, thanks for the PR :)

**Comment by Ci7rix** [comment]
> Nice, thanks for the PR :)

My pleasure :)

**Pull request merged**
